name: Push (main)

on:
  push:
    branches:
      - main
    paths:
      - "rockcraft.yaml"
      - ".github/workflows/**.yaml"

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  test:
    needs: build
    uses: ./.github/workflows/test.yaml

  scan:
    needs: build
    uses: ./.github/workflows/scan.yaml

  publish:
    needs:
      - test
      - scan
    uses: ./.github/workflows/publish.yaml
